# ワークフローの名前
name: Release Netlify Page

# 起動のタイミング
# 今回はmasterブランチへのpush
on:
  push:
    branches:
      - master

# ジョブの定義
jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['12.x']

    # 各ステップの実行
    steps:

    # チェックアウト
    - uses: actions/checkout@v2

    # 使用するnodeのバージョンを指定
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node-version }}

    # パッケージのインストールとアプリのビルド
    - name: install and build
      run: |
        yarn install
        yarn build
      #env:
      #  CI: true

    # パッケージのインストールとアプリのビルド
    - name: check pict
      run: (cd tools/ && npm install && node index.js)

    # Netlifyにデプロイ
    - name: deploy
      run: npx netlify-cli deploy --dir=./docs --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}